"""Константы."""

# User
EMAIL_MAX_LENGTH = 254
NAME_MAX_LENGTH = 150

# Urlshort
MIN_HASH_LENGTH = 8
MAX_HASH_LENGTH = 10
HASH_FIELD_LENGTH = 15
MAX_URL_LENGTH = 256

# Tag
TAG_MAX_LENGTH = 32
SLUG_REGEXVALIDATOR = r"^[-a-zA-Z0-9_]+$"

# Ingredient
INGREDIENT_MAX_LENGTH = 128
UNIT_INGREDIENT_MAX_LENGTH = 64

# Recipe
RECIPE_MAX_LENGTH = 256
COOKING_MIN_TIME = 1

# RecipeIngredient
AMOUNT_MIN = 1
