# Generated by Django 4.2.23 on 2025-06-19 08:12

"""Начальная миграция приложения urlshort: создание модели ShortLink."""

from django.db import migrations, models
import urlshort.models


class Migration(migrations.Migration):
    """Миграция для создания модели ShortLink."""

    initial = True

    dependencies: list = []

    operations = [
        migrations.CreateModel(
            name="ShortLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_url",
                    models.CharField(
                        max_length=256, verbose_name="Оригинальная ссылка"
                    ),
                ),
                (
                    "url_hash",
                    models.CharField(
                        default=urlshort.models.generate_hash,
                        max_length=15,
                        unique=True,
                        verbose_name="Хэш ссылки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сокращённая ссылка",
                "verbose_name_plural": "Сокращённые ссылки",
                "ordering": ["-id"],
            },
        ),
    ]
